Event unregistration deadline
webkom/lego-webapp pull request #2089
Opened 2021-01-13 19:58 UTC by iselinee

Add the ability to set a deadline (hard) for unregistration before an event, separate from the registration deadline. 
From this:
![Skjermbilde 2020-10-13 kl  22 26 27](https://user-images.githubusercontent.com/43182013/104503492-6d9de900-55e1-11eb-9d62-94f24c2cd14e.png)

To this:

![Skjermbilde 2020-11-03 kl  20 25 36](https://user-images.githubusercontent.com/43182013/104503614-9625e300-55e1-11eb-8cd8-a4a7944d523c.png)

![Skjermbilde 2020-11-03 kl  20 23 15](https://user-images.githubusercontent.com/43182013/104503569-87d7c700-55e1-11eb-91fb-9f1f78fc1176.png)

![Skjermbilde 2020-11-03 kl  20 25 12](https://user-images.githubusercontent.com/43182013/104503577-89a18a80-55e1-11eb-906b-e351e1d3b15e.png)

2021-01-19 15:49 UTC, ingraso commented on app/routes/events/components/EventEditor/index.js
> +              /* Need a checkbox to separate absolute registration and unregistration deadline */
These comments (357-360) could be merged to one multi-line comment

2021-01-19 15:49 UTC, ingraso commented on app/routes/events/components/EventDetail/index.js
> +            key: 'Avregistrering stenger' /*Endre teksten*/,
Is this comment supposed to be here?

2021-01-19 18:37 UTC, erlingfn commented on app/routes/events/EventEditRoute.js
> +      unregistrationDeadline:
Since this now defined two places, would it be possible to only have it in one route/in utils and import it?

2021-01-19 18:44 UTC, erlingfn commented on app/routes/events/components/EventEditor/index.js
> +                  label="Separate frister"
What about _"Separat avregistreringsfrist"_? In my opinion it would be a little bit more unambigous.

2021-01-19 18:53 UTC, erlingfn requested changes
Looks good! Just a few cosmetic changes

2021-01-26 09:35 UTC, erlingfn approved these changes
Looks good to me!

2021-01-26 20:15 UTC, PeterJFB approved these changes
lgtm^.^

2021-02-05 22:57 UTC, merged