add sorting selector for quotes
webkom/lego-webapp pull request #3074
Opened 2022-09-28 17:49 UTC by Arashfa0301

Added sorting selector for quotes which now enables users to sort after Imojis 🤌

2022-09-29 08:02 UTC, eikhr requested changes
Good work! I've commented on some small things and a small problem is that it's not possible to go directly to `/quotes/?ordering=-reaction_count` as it will just change to the default quote sorting.

2022-10-01 17:56 UTC, Arashfa0301 commented on app/routes/quotes/components/QuotePage.js
> +    value: '/quotes',
Absolutely correct

2022-10-01 17:56 UTC, Arashfa0301 commented on app/routes/quotes/components/QuotePage.js
> +          name="form-field-name"
Can't forget the name:)

2022-10-01 17:57 UTC, Arashfa0301 commented on app/routes/quotes/components/QuotePage.js
> +  const [ordering: Option, setOrdering] = useState(filterRegDateOptions[0]);
Learn something new everyday

2022-10-01 19:00 UTC, eikhr approved these changes

2022-10-02 12:49 UTC, ivarnakken commented
Please add some illustrations of the result 😄

2022-10-02 14:23 UTC, eikhr commented
I just realized you didn't fix the thing about going directly to the sorted page. It always resets to default sorting regardless of the url. Do you want to look into that, too?

2022-10-12 16:40 UTC, Arashfa0301 commented
> I just realized you didn't fix the thing about going directly to the sorted page. It always resets to default sorting regardless of the url. Do you want to look into that, too?

It is finally fixed now. Thank you for your precious feedback

2022-10-12 20:07 UTC, eikhr approved these changes

2022-10-12 20:48 UTC, merged