Improve styling of the calendar
webkom/lego-webapp pull request #3470
Opened 2023-01-24 19:02 UTC by haukkagu

# Notable changes
- Changed design of the event entry to a pill design
- Added time and place for the event in the popover
- Events that last over multiple days will be shown on each day they take place.
- Made the calendar taller and decreased the font size for the day numbers and weekend heading.

In addition to many minor changes like centering the registration pill in the popover, improving variable names, changing colors etc.

# Result
### Example 1 (light mode):
![before1](https://user-images.githubusercontent.com/66320400/214376828-1b171324-2386-4c73-a2bc-1669248fbffd.png)
![after1](https://user-images.githubusercontent.com/66320400/214376808-d319d3fe-160c-4059-8c81-27fbf8614fd8.png)

### Example 2 (dark mode):
![before2](https://user-images.githubusercontent.com/66320400/214376825-73361dd0-0057-4a03-b7d4-dbbb738e430f.png)
![after2](https://user-images.githubusercontent.com/66320400/214376814-7cf7d95d-c66d-41da-aeb9-526e0ff267e3.png)

### Example 3 (another month with popover):
![before4](https://user-images.githubusercontent.com/66320400/214382522-3eb5a8a5-31d0-4c2c-9287-69016c2dc9b8.jpg)
![after4](https://user-images.githubusercontent.com/66320400/214382517-1741a2df-fc56-49e8-baa6-981080f6b9ad.jpg)

# Testing

- [sort of ] I have thoroughly tested my changes.
I have scrolled through the calendar and all the months look fine.

# Notes
- I mentioned that I wanted to improve the styling of the calendar on phones. That will be implemented in a separate PR.
- I realize that the Pill-component can be used for the event pills instead of implementing it myself. I remember trying to do that when I first started on this project, but couldn't get it to work. However, I may give it another shot now.

---

Resolves [this linear task](https://linear.app/abakus-webkom/issue/ABA-176/improve-the-layout-of-the-calendar)

2023-01-24 19:24 UTC, ivarnakken requested changes
Looks much much better! Great work! 😍 😍 

Ideally I'd want the bars to overflow over the borders when the event stretches over multiple days, but that can be fixed later 👍🏼 

Btw, there are some linting issues as well. Please amend those changes to a previous commit.

2023-01-24 19:24 UTC, ivarnakken commented on app/routes/events/utils.ts
> +export const TEXT_COLOR_CONSTANTS: Record<EventType, string> = {
This doesn't have to exported, or?

2023-01-24 21:40 UTC, haukkagu commented on app/routes/events/components/Calendar.css
> +  grid-template-columns: repeat(7, 14.2857%);
Will do!

2023-01-24 21:40 UTC, haukkagu commented on app/routes/events/utils.ts
> +export const TEXT_COLOR_CONSTANTS: Record<EventType, string> = {
Nope, you're right.

2023-01-24 23:55 UTC, LudvigHz approved these changes
Awesome :+1: 
Just some small comments, otherwise it looks good to go!

2023-01-24 23:55 UTC, LudvigHz commented on app/routes/events/components/CalendarCell.tsx
> +      )
Is it possible to split this up a bit? Or at least add a comment explaining it :sweat_smile:

2023-01-24 23:55 UTC, LudvigHz commented on app/routes/events/utils.ts
> +};
if you slap an `as const` here you should get stronger type checking :)

2023-01-29 17:04 UTC, LudvigHz approved these changes
LGTM :shipit:

2023-01-29 17:05 UTC, LudvigHz commented
@haukkagu Just fix lint and we can get this in :) And also change your last commit message to something more descriptive at the same time :grimacing:

2023-01-29 17:10 UTC, ivarnakken approved these changes
Looks perfect now!

But like @LudvigHz said, please make the commit message more descriptive ❤️

2023-01-29 17:22 UTC, haukkagu commented
Isn't it a good idea to squash the commits before merging? Doesn't that make the name of the last commit irrelevant?
Also, the linting fails on code I haven't touched. What should I? @LudvigHz @ivarnakken

2023-01-29 19:31 UTC, merged