Add models for data types fetched from LEGO
webkom/lego-webapp pull request #3510
Opened 2023-02-02 10:11 UTC by eikhr

Adds typescript types for all entity types from LEGO with different types for the different serializers. They are in `app/store/models`. I have also added an Unknown<entityName> type for each entity which is simply a union of the different serializers, which is used f.ex. in the redux store where we can't know which of the types it is. 

I have also gone through the announcement, article and company (not bdb yet) pages and replaced the types with these new ones.

# Result

There should be no functional difference.

# Testing

- [ ] I have thoroughly tested my changes.

Please describe what and how the changes have been tested, and provide instructions to reproduce if necessary.

---

2023-02-02 21:16 UTC, ivarnakken requested changes
Awesome job!!!! 💯 💯 This is very satisfying and removes a ton of technical debt!

Besides my mostly picky comments, I'm not a big fan of having duplicate types, one in our `app/models.ts` and one in `app/store/models/*.d.ts`. I don't see why we need both. Anyways, fantastic work! And just so it's said, you don't need to resolve all of my comments.

2023-02-02 21:16 UTC, ivarnakken commented on app/store/models/entities.ts
> +  CompanyInterests = 'companyInterest', // Why the fuck is this not plural?
😆

2023-02-02 21:16 UTC, ivarnakken commented on app/store/models/SurveySubmission.d.ts
> +interface SurveySubmission {
Is this used?

2023-02-02 21:16 UTC, ivarnakken commented on app/store/models/Poll.d.ts
> +  comments: unknown; // TODO: is it even possible to comment on polls?
Interesting.

2023-02-07 21:32 UTC, eikhr commented
I'm intending on removing all the types from `app/models.ts`, but they are still in use in most of the app so it will have to wait.

2023-02-07 21:47 UTC, eikhr commented on app/routes/announcements/components/AnnouncementsCreate.tsx
> +  handleSubmit: (arg0: (...args: Array<any>) => any) => any;
one step forward, two back or something...

2023-02-07 21:49 UTC, eikhr commented on app/store/models/SurveySubmission.d.ts
> +interface SurveySubmission {
It will be

2023-02-07 21:53 UTC, ivarnakken approved these changes
We can iterate on the nitpicks later 💯

2023-02-07 22:10 UTC, merged