Create TextWithIcon component
webkom/lego-webapp pull request #3590
Opened 2023-02-18 20:16 UTC by ingraso

# Description

Text is displayed with icons throughout the whole webapp. However, there is no component or common way of doing this. With the `<TextWithIcon />` component there is now a generalized component that can be used for this purpose. An example of usage can be seen here:
![image](https://user-images.githubusercontent.com/43182025/219891377-e75cf9ba-4055-495c-9f5e-422645eec77c.png)

There should be no visual changes to the text with icons.

Also fixes some TS errors and moves the tooltip on `<EventDetail />` to be on the icon rather than the text.

# Result
**Before**
![image](https://user-images.githubusercontent.com/43182025/219890758-1d3a6c7b-5234-4c53-a236-e243db0054f5.png)

**After**
![image](https://user-images.githubusercontent.com/43182025/219890642-3cad6663-bc9a-49d6-9efd-037e2655e013.png)

# Testing

- [x] I have thoroughly tested my changes.

Tested by clicking through where changes have been done.

---

Resolves ABA-293

2023-02-18 21:39 UTC, ollfkaih requested changes

2023-02-18 21:39 UTC, ollfkaih commented on app/routes/events/components/EventDetail/index.tsx
>        : () => follow(currentUser.id, event.id);
Types were wrong here, but these lines are correct (#3592)

2023-02-19 16:52 UTC, LudvigHz approved these changes
LGTM

2023-02-19 21:25 UTC, ivarnakken approved these changes
Nice to standardize stuff like this 💯 Just fix up in Olav's comment and we should be good here

2023-02-22 06:21 UTC, ollfkaih approved these changes
Looks good now!

2023-02-22 14:24 UTC, merged