Improve standardizations across events and joblistings
webkom/lego-webapp pull request #3838
Opened 2023-04-25 16:38 UTC by mattiastofte

# Description

This is a work-in-progress branch, so I'm not finished yet. There are a lot of small tweaks included to standardize and modernize the design across the webapp's three main sections, respectively "arrangementer", "karriere" and "om abakus". 

**On all the pages:**
I've added a title that is similarly styled across the three pages.

**On the karriere-page:**
I've refactored the filters into a neat sidebar with a bg-color similar to the updated "om abakus"-page. I've also made some improvements to the margins/paddings as well as upping the thickness of the dividers. Lastly I moved the create new job listing button to the bottom. I'm thinking about replacing this button with a button similar to that on the "arrangementer" page (for consistency).

**On the arrangementer-page:**
I replaced the NavLinks buttons with icons, as they were not optimal aesthetically speaking and took a lot of space. I've also added a round indicator selector so that you easily can see which view you are using. I'm not completely happy with this design yet, so I'm looking to improve it. I also removed the filter icon :,( since it just looked really messy in-between the elements. Lastly I moved the "opprett nytt" button to be beside the newly created title "arrangementer", for a cleaner look. This is also how I'm thinking about doing the "create new job listing"-button later.

Again this PR is **not finished**, there is still a lot of improvements to do, but I would appreciate feedback along the way:-) Basicly the goal with this PR is to make everything similar to the new "karriere-page" as I think this one turned out very cleanly.

# Result

If you've made visual changes, please include **before** and **after** images, preferably with a description. Make sure they do not contain any real user information.

**before:**

![image](https://user-images.githubusercontent.com/37273026/234343724-0501c4e9-1e5a-48c7-9d62-af56ccdc9e12.png)

![image](https://user-images.githubusercontent.com/37273026/234343792-4ad35a8c-fb7f-4103-9bd7-99ecb7f5f152.png)

![image](https://user-images.githubusercontent.com/37273026/234343957-12faa85a-66b8-4474-9e4a-b0e0ff9a9765.png)

**after:**

![image](https://user-images.githubusercontent.com/37273026/234343401-55f2cf15-64cb-47fb-a5b4-b29cd60c9a7a.png)

![image](https://user-images.githubusercontent.com/37273026/234343504-d024582d-ebb3-42df-90ca-f1216bf37cc1.png)

![image](https://user-images.githubusercontent.com/37273026/234343588-ec891b5e-81aa-4740-ab99-1ca6287cb9a8.png)

# Testing

- [x] I have thoroughly tested my changes.
- [x] I have tested my changes on mobile.

Resolves ... (either GitHub issue or Linear task)
Closes #ABA-435

2023-04-25 17:12 UTC, ivarnakken commented
This looks really good already!! 😍 😍 

Some comments solely based on the given images:
1. I'd like the filtering on _/events_ to be on the side of the list, like on _/joblistings_. They should use the same wrapper component.
2. I'd like the filtering to be on the left side, so that it matches _/pages_ and other sites (e.g. finn.no).

2023-05-30 07:54 UTC, ivarnakken requested changes
Again, this looks very nice. Would love to merge it in sometime soon 😛

2023-05-30 07:54 UTC, ivarnakken commented on app/routes/events/components/EventList.css
> +  font-weight: 500;
The added `font-weight` shouldn't be necessary since `.heading` is used on an `h2` tag.

2023-05-30 07:54 UTC, ivarnakken commented on app/routes/events/components/Toolbar.css
> +}
Please just use the `Flex` component for this. Less CSS is better CSS.

2023-05-30 07:54 UTC, ivarnakken commented on app/routes/events/components/Toolbar.css
> +}
Missing new line

2023-05-30 07:54 UTC, ivarnakken commented on app/routes/events/components/Toolbar.tsx
> +        <Icon name="calendar-clear-outline" size={26}></Icon>
```suggestion
        <Icon name="calendar-clear-outline" size={26} />
```

2023-05-30 07:54 UTC, ivarnakken commented on app/routes/joblistings/components/JoblistingPage.css
> +  padding: 0px 0px 0px 0px;
```suggestion
  padding: 0;
```

2023-05-30 07:54 UTC, ivarnakken commented on app/routes/joblistings/components/JoblistingRightNav.tsx
> +      className={styles.filterCheckbox}
This doesn't seem to be used?

2023-05-30 07:54 UTC, ivarnakken commented on app/routes/pages/components/Sidebar.css
> +  font-size: 24px;
See comments above regarding font-sizes.

2023-05-30 07:57 UTC, mattiastofte commented
> Again, this looks very nice. Would love to merge it in sometime soon 😛 

I've been a little inactive on this but I'll try my best of finish this before summer 🤓

2024-07-06 12:53 UTC, eikhr commented
Similar changes implemented in #4712

2024-07-06 12:53 UTC, closed without merging