Implement github usernames on profiles.
webkom/lego-webapp pull request #3901
Opened 2023-05-13 14:11 UTC by jonasdeluna

# Description

Implement github username on profile. Addable from the user settings.

# Result

![image](https://github.com/webkom/lego-webapp/assets/113468143/f853eba6-75a5-4d3f-b89f-f29343dfa665)

![image](https://github.com/webkom/lego-webapp/assets/113468143/6e8ae2e4-576c-4149-9995-7a0dcb05c3cc)

# Testing

- [x] I have thoroughly tested my changes.

---

Resolves ... ABA-479
Depends on: https://github.com/webkom/lego/pull/3389

2023-05-13 14:55 UTC, ivarnakken requested changes
Cool! :octocat:

Some minor comments and thoughts

2023-05-13 14:55 UTC, ivarnakken commented on app/routes/users/components/UserSettings.tsx
> +              label="Github Brukernavn"
```suggestion
              label="GitHub-brukernavn"
```

2023-05-13 14:55 UTC, ivarnakken commented on app/routes/users/components/UserProfile.tsx
> +          </Flex>
I'd prefer to only have the link under "Brukerinfo".

2023-05-13 14:55 UTC, ivarnakken commented on app/routes/users/components/UserProfile.tsx
> +  githubUsername: 'Github Brukernavn',
```suggestion
  githubUsername: 'GitHub-brukernavn',
```

2023-05-13 14:55 UTC, ivarnakken commented on app/routes/users/components/UserProfile.tsx
> +  githubUsername: 'Github Brukernavn',
Or just "GitHub". And I'm actually leaning towards just "GitHub".

2023-05-13 14:55 UTC, ivarnakken commented on app/utils/validation.ts
> +  (message = 'Ikke et gyldig Github brukernavn') =>
```suggestion
  (message = 'Ikke et gyldig GitHub-brukernavn') =>
```

2023-05-14 12:36 UTC, LudvigHz approved these changes

2023-05-14 12:36 UTC, LudvigHz commented on app/routes/users/components/UserProfile.tsx
> +const githubFieldrender = (field, value) => (
nitpic, but
```suggestion
const githubFieldRender = (field, value) => (
```

2023-05-14 12:36 UTC, LudvigHz commented on app/routes/users/components/UserProfile.tsx
> +const githubFieldrender = (field, value) => (
Also, please type your code :) (`field` and `value` are missing types here)

2023-05-14 12:36 UTC, LudvigHz commented on app/routes/users/components/UserSettings.tsx
> +  githubUsername: [isValidGithubUsername()],
It's a _bit_ unnecessary to have this both in the frontend and backend, but not very important.

2023-05-14 12:40 UTC, LudvigHz commented
A note on the design. The `Github Brukernavn` text is a little ugly imo, and I think just using the github icon as the label would be cleaner :)

I.e. sort of like this:
![image](https://github.com/webkom/lego-webapp/assets/42850232/d55a559c-baa2-4159-b2d7-3133c372e962)

2023-05-26 11:32 UTC, ivarnakken commented on app/routes/users/components/UserProfile.css
> +}
This is not used

2023-06-08 10:53 UTC, ivarnakken commented on app/routes/users/components/UserProfile.tsx
> +  githubUsername: 'Github',
```suggestion
  githubUsername: 'GitHub',
```

2023-07-12 18:14 UTC, ivarnakken commented
@jonasdeluna What's the status on this? I see you wanted to implement for LinkedIn as well, but I believe that can be separated into a different PR.

2023-08-30 15:53 UTC, jonasdeluna commented
> @jonasdeluna What's the status on this? I see you wanted to implement for LinkedIn as well, but I believe that can be separated into a different PR.

Ooops I was sleeping :| I fixed the last comments, working on getting the backend validators to work properly because they were somehow buggy...

2023-09-01 15:16 UTC, merged