Add dropdown menu to navbar
webkom/lego-webapp pull request #4188
Opened 2023-10-13 21:08 UTC by haukkagu

# Description
Adds a simple dropdown menu you hover over the navbar.

# Result

**Before**

[Screencast from 2023-10-13 22-53-19.webm](https://github.com/webkom/lego-webapp/assets/66320400/ede42d98-12dc-40ac-b256-ef42e99bd3a8)

**After**

Light mode:

![Screencast from 2023-10-13 22-52-12.webm](https://github.com/webkom/lego-webapp/assets/66320400/ebe511ce-a8cf-497d-9e1b-ffbd306947a9)

Dark mode:

# Testing

- [x] I have thoroughly tested my changes.

Everything works... EXCEPT this tiny [bug](https://linear.app/abakus-webkom/issue/ABA-606/following-a-link-to-om-abakus-does-not-open-the-appropriate-tab-if) that I encountered. It is not caused by the changes in this PR tho, so it will need to be fixed in a separate PR.

---

Resolves ABA-143

2023-10-13 21:16 UTC, ivarnakken requested changes
Thanks for picking this up! It looks nice!

2023-10-13 21:16 UTC, ivarnakken commented on app/components/Header/Navbar/ItemList.tsx
> +    <div className={styles.items}>
Let this be a Flex component instead

2023-10-13 21:16 UTC, ivarnakken commented on app/components/Header/Navbar/Item.css
> +}
```suggestion
.item {
  color: var(--lego-font-color);
  cursor: pointer;
  padding: 0.4rem;
  width: 250px;
  border-radius: var(--border-radius-md);
  
  &:hover {
    background-color: var(--additive-background);
  }
}
```

2023-10-13 21:16 UTC, ivarnakken commented on app/components/Header/Navbar/Item.css
> +  transition: 0.25s;
Use transition variables instead

2023-10-14 09:25 UTC, haukkagu commented
I think the back ground color of a highlighted item looks a bit weird on darkmode, t looks better when I change the background color from `color-gray-1` to `color-gray-2` in my opinion:

[Screencast from 2023-10-14 11-22-03.webm](https://github.com/webkom/lego-webapp/assets/66320400/678f2a9e-21de-4879-b993-ecde71d84f58)

However, that color looks horrible on light mode. Do you have any ideas on what to do? Could I make my own color, or should we just leave it be?

2023-10-18 16:45 UTC, itsisak approved these changes
Looks great! Well done💯

2023-10-24 22:29 UTC, ivarnakken approved these changes
Looks good!

2023-10-24 22:29 UTC, ivarnakken commented on app/components/Header/Navbar/EventsDropwdown.css
> +  flex-direction: column;
This seems to be unused

2023-10-24 22:29 UTC, ivarnakken commented on app/components/Header/Navbar/ItemList.tsx
> +    <Flex column={true}>
```suggestion
    <Flex column>
```
Same thing

2023-10-24 22:47 UTC, merged

2023-10-25 01:57 UTC, norbye commented
Found a smol bug(: on mobile, the navbar is still displayed.. so you might've gotten a mail that it has been deployed, but I'm only deploying until the commit before this one right now

Visual of the bug; (should've only displayed the logo and the icons, not the navbar text)
<img width="300" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/0e4ce853-d7b2-4e5d-9432-bfbceec78dde">

2023-10-25 08:19 UTC, haukkagu commented
@norbye Good catch! Seems like I forgot to import variables.css in the css file 🙃. I'll fix this right away