Hide Contact Tracing Field in EventEditor
webkom/lego-webapp pull request #4231
Opened 2023-10-24 16:24 UTC by AdrianAndersen

# Description

This PR hides the field for contact tracing, so that no one can enable it by mistake. I think the rest of the functionality should remain in the codebase though, so it is really easy to just make this visible if we ever encounter another pandemic. 

# Result

The field in the EventEditor is hidden. 

# Testing

- [X] I have thoroughly tested my changes.

---

Resolves ABA-183

2023-10-24 18:22 UTC, ivarnakken requested changes
Please just remove it, and we'll revert the commit if it comes to that

2023-10-24 18:33 UTC, AdrianAndersen commented
Sure, we can do that. I assume you mean to remove _all traces_ of the contact_tracing functionality, including the backend models, @ivarnakken?

2023-10-24 18:33 UTC, ivarnakken commented
> Sure, we can do that. I assume you mean to remove all traces of the contact_tracing functionality, including the backend models, @ivarnakken?

Yes

2024-02-20 19:44 UTC, AdrianAndersen commented
Superseded by https://github.com/webkom/lego-webapp/pull/4476

2024-02-20 19:44 UTC, closed without merging