Show waiting list position even if there are multiple pools
webkom/lego-webapp pull request #4983
Opened 2024-09-23 14:19 UTC by eikhr

DEPENDS ON BACKEND PR: https://github.com/webkom/lego/pull/3642 (that is why cypress fails)

# Description

Show waiting list position for each applicable pool if there are multiple pools in the event.

The waitlist position is calculated for each pool by looping through the waiting list and counting how many people before you are applicable for the given pool. This depends on a backend change, that includes the ids of all groups (including inherited) for each registration on the waiting list. https://github.com/webkom/lego/pull/3642

# Result

- [x] Changes look good on both light and dark theme.
- [x] Changes look good with different viewports (mobile, tablet, etc.).
- [x] Changes look good with slower Internet connections.

> [!CAUTION]
> Make sure your images do not contain any real user information.

**Before:**
![Screenshot 2024-09-23 at 16 16 38](https://github.com/user-attachments/assets/c3fac255-6da1-4038-9d42-602259b475c4)

**After:**
This user is first on the waiting list and has access to only the "Abakus" pool:
<img width="344" alt="Screenshot 2024-09-24 at 17 33 44" src="https://github.com/user-attachments/assets/b3f6af5b-da30-4cfc-8e7c-7eda2f54291d">

This user is second on the waiting list, but is the only one with access to the "Webkom" pool:
<img width="344" alt="Screenshot 2024-09-24 at 17 32 47" src="https://github.com/user-attachments/assets/c7a0f2b8-8988-4bac-a9d3-1cb0c0695459">

Event with only one pool/merged pools:
<img width="344" alt="Screenshot 2024-09-24 at 21 22 20" src="https://github.com/user-attachments/assets/67b75203-dfcf-4384-bfeb-159cf30a8843">

# Testing

- [x] I have thoroughly tested my changes.

I have created a few different events with different conditions, and it has calculated and shown the correct positions in all my tests:)

---

Resolves ABA-1070

2024-09-23 14:34 UTC, falbru approved these changes
A very nice feature!

2024-09-23 15:32 UTC, ivarnakken commented
There's something off about the wording of "Din plass i ventelisten for Abakus er 2 og for Webkom er 1"

Perhaps something like "Din plass i ventelistene er 2 for Abakus og 1 for Webkom", or "Din plass i ventelisten for Abakus er 2 og for  Webkom er **den** 1"?

2024-09-24 15:36 UTC, eikhr commented
> There's something off about the wording of "Din plass i ventelisten for Abakus er 2 og for Webkom er 1"
> 
> Perhaps something like "Din plass i ventelistene er 2 for Abakus og 1 for Webkom", or "Din plass i ventelisten for Abakus er 2 og for Webkom er **den** 1"?

Agree. I changed it to "Dine plasser i ventelistene er 2 for Abakus og 1 for Webkom". I still think it feels a bit confusing, but it is very rare to have access to multiple pools, so I don't want to spend too much time perfecting it:)

2024-09-25 16:48 UTC, norbye requested changes
stonks!

2024-09-25 16:48 UTC, norbye commented on app/routes/events/components/EventDetail/getWaitingListPosition.ts
> +  const applicablePools = pools.filter((p) =>
```suggestion
  const applicablePools = nonWaitingListPools.filter((p) =>
```

2024-09-25 16:48 UTC, norbye commented on app/routes/events/components/EventDetail/getWaitingListPosition.ts
Would be nice if you didn't make one letter variable names such as `p`

2024-09-25 17:43 UTC, Bestem0r approved these changes
Nice!

2024-09-25 20:52 UTC, norbye approved these changes

2024-09-25 20:52 UTC, norbye commented on app/routes/events/components/EventDetail/getWaitingListPosition.ts
> +      (r) => isPermittedInPool(r.user, pool),
```suggestion
      (registration) => isPermittedInPool(registration.user, pool),
```

2024-09-25 20:58 UTC, merged