Avoid flickering when toggling notifications dropdown
webkom/lego-webapp pull request #5075
Opened 2024-10-19 11:03 UTC by ivarnakken

# Description

Solved by optimistically marking all as read and seen (not sure what the difference is?)

# Result

- [x] Changes look good on both light and dark theme.
- [x] Changes look good with different viewports (mobile, tablet, etc.).
- [x] Changes look good with slower Internet connections.

<table>
    <tr>
        <td>Before</td>
        <td>After</td>
    </tr>
    <tr>
        <td>
			<video src="https://github.com/user-attachments/assets/ba568008-2a40-4eea-9326-7747b9f38555" />
        </td>
        <td>
			<video src="https://github.com/user-attachments/assets/1b427c4c-98bf-48c7-91b4-b1109acf30c9" />
        </td>
    </tr>
</table>

# Testing

- [x] I have thoroughly tested my changes.

See videos above

2024-10-22 18:40 UTC, Bestem0r approved these changes
Looks good to me!

2024-10-23 08:59 UTC, falbru approved these changes

2024-10-23 10:11 UTC, emillub commented
LGTM🔥

2024-10-23 16:48 UTC, eikhr requested changes

2024-10-23 16:48 UTC, eikhr commented on app/components/HeaderNotifications/index.tsx
>            dispatch(markAllNotifications());
Mark as completed on `NotificationsFeed.MARK_ALL.BEGIN` in the reducer instead of dispatching wrong actions

2024-10-23 16:55 UTC, jonasdeluna approved these changes
Awesome!

2024-10-23 17:17 UTC, eikhr approved these changes

2024-10-23 18:22 UTC, merged

2024-10-30 14:05 UTC, sondrejk reviewed
What does it mean to optimistically mark all as read?