Make qoute approving intuitive
webkom/lego-webapp pull request #5163
Opened 2024-11-06 18:50 UTC by jennymul

# Description
Remove "Fjern godkjenning" as an option when a qoute is approved. When trying to delete a qoute, remove "Godkjenn" when "Er du sikker?" comes up.

![image](https://github.com/user-attachments/assets/95b77661-0b16-407c-aeb7-b596d313b896)

- [X] Changes look good on both light and dark theme.
- [X] Changes look good with different viewports (mobile, tablet, etc.).
- [X] Changes look good with slower Internet connections.

- [X] I have thoroughly tested my changes.

2024-11-06 22:40 UTC, norbye reviewed
The `deleting` variable seems to have about the same behaviour as the new thingy you added - is there any reason you did not use that one instead?

2024-11-06 22:40 UTC, norbye commented on app/routes/quotes/components/Quote.tsx
> +  const [pippi, setPippi] = useState(true);
🤔

2024-11-10 19:38 UTC, ivarnakken requested changes
Some refactoring needed, but I agree that this can be more intuitive!

2024-11-10 19:38 UTC, ivarnakken commented on app/routes/quotes/components/Quote.tsx
> +                          {'Godkjenn'}
```suggestion
                          Godkjenn
```

2024-11-10 19:38 UTC, ivarnakken commented on app/routes/quotes/components/Quote.tsx
> +                    {!quote.approved && pippi ? (
```suggestion
                    {!quote.approved ? (
```
?

2024-11-10 19:38 UTC, ivarnakken commented on app/routes/quotes/components/Quote.tsx
> +                      <div></div>
Instead of using a ternary, just use && so that we don't need empty divs like this in the dom

2024-11-10 19:38 UTC, ivarnakken commented on app/routes/users/components/UserProfile/UserProfile.module.css
not related to this PR

2024-11-10 19:38 UTC, ivarnakken commented on app/routes/users/components/UserProfile/index.tsx
Again, not relevant to this PR hehe

2026-08-27 17:08 UTC, closed without merging