Support date range filtering on events
webkom/lego-webapp pull request #5259
Opened 2024-12-29 13:10 UTC by ivarnakken

# Description

Highly requested and very useful!

Had to make some changes to the date picker and query hook.

# Result

- [x] Changes look good on both light and dark theme.
- [x] Changes look good with different viewports (mobile, tablet, etc.).
- [x] Changes look good with slower Internet connections.

<img width="1177" alt="image" src="https://github.com/user-attachments/assets/71843fac-5909-4db8-b1c1-5601d5e7a068" />

# Testing

- [x] I have thoroughly tested my changes.

Tested on hard refreshes, many different date ranges, together with the `query.showPrevious` and the "Load more" button.

2025-01-04 21:39 UTC, falbru requested changes
Awesome feature!

Found a bug where I could pick a start date that was after the end date:

![image](https://github.com/user-attachments/assets/daf269db-20d4-4c0b-a46c-73e65bd6852e)

I first selected 1, then 16 and then 23.

2025-01-05 10:38 UTC, ivarnakken commented
> Found a bug where I could pick a start date that was after the end date:

Nice catch :) I noticed there was some buggy behaviour but it was difficult to reproduce; thanks for the example. I'll try to make it less prone to bugs but there are a ton of edge cases to this .. 😩

2025-01-05 13:24 UTC, ivarnakken commented
I made several improvements to the date picker now - try it out! It should now cover all edge cases pretty nicely. I tried to follow a similar logic to [shadcn](https://ui.shadcn.com/docs/components/date-picker) and [NextUI](https://nextui.org/docs/components/date-range-picker)

2025-01-05 20:59 UTC, falbru approved these changes
Awesome! Works for me now!

2025-01-06 19:22 UTC, merged